name: Build and publish docker images

on:
  workflow_call:
    inputs:
      app-gh-ref:
        required: true
        type: string
        default: 'refs/heads/develop'
      reg_name:
        required: true
        type: string
        default: 'docker.io'
      reg_login:
        required: true
        type: string
        default: 'librebooking'
  workflow_dispatch:
    inputs:
      app-gh-ref:
        required: true
        description: 'Application github reference'
        default: 'refs/heads/develop'
      reg_name:
        required: true
        description: 'Registry name'
        default: 'docker.io'
      reg_login:
        required: true
        description: 'Registry login'
        default: 'librebooking'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout github repository
        uses: actions/checkout@v4
        with: 
          repository: ${{ github.repository }}
      -
        name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.reg_name }}
          username: ${{ inputs.reg_login }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Get the docker image metadata
        id: get_meta
        run: |
          APP_TAG=$(basename ${{ inputs.app-gh-ref }})
          ACT_TAG=$(basename ${{ github.ref }})
          if [ "${APP_TAG}" \< "2.8.6" ]; then 
            PHP_VERSION="7"
          else
            PHP_VERSION="8"
          fi
          echo "APP_TAG=${APP_TAG}" >> "$GITHUB_OUTPUT"
          echo "ACT_TAG=${ACT_TAG}" >> "$GITHUB_OUTPUT"
          echo "PHP_VERSION=${PHP_VERSION}" >> "$GITHUB_OUTPUT"
      -
        name: Set the docker image metadata
        id: set_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository_owner }}/librebooking
          tags: |
            type=raw,suffix=-${{ steps.get_meta.outputs.ACT_TAG }},value=${{ steps.get_meta.outputs.APP_TAG }}
            type=raw,value=${{ steps.get_meta.outputs.APP_TAG }}
      -
        name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            PHP_VERSION=${{ steps.get_meta.outputs.PHP_VERSION }}
            APP_GH_REF=${{ inputs.app-gh-ref }}
          tags: ${{ steps.set_meta.outputs.tags }}
          push: true
